---
title: "Examen_II_G2-C37963-AlessandroUma-aVega"
author: "Alessandro Umaña Vega"
format: html
editor: visual
---
#Librerías
```{r}
#se agrega las librerías que se usarán
library(readr)
library(tidyverse)
library(ggplot2)
```
 
#Carga la base de datos
```{r}
#se carga el archivo excel y se pone que el salario es una variable de tipo character para que aparezca la coma de los salarios
moras <- read_csv("C:/Users/aless/OneDrive/Escritorio/Cursos de computación/Herramientas de Datos I/Examen virtual 2/moras.txt", 
    col_types = cols(SALARIO = col_character()))

#se usa la funcion gsub para cambiar la coma por un punto y despues se pone la columna que se quiere cambiar
moras$SALARIO <- gsub(",", ".", moras$SALARIO)

#se cambia el tipo de variable de la columna a una de tipo numérico
moras$SALARIO <- as.numeric(moras$SALARIO)
view(moras)
```

#Resumen 5 números
```{r}
#se crea resumen donde se calculara las 5 variables usando summary y select para que resuma solamente las variables que se deseen.
resumen <- moras %>%
  select(c(SALARIO, EDAD)) %>%
  summary()
resumen


  
```

#Z-score
```{r}
#con mutate se creara las dos columnas con los valores atípicos haciendo uso de funciones como mean y sd para calcular la desviación estandar, también se usará la funcion abs para sacar el valor absoluto del resultado del z-score.

#note que en R los valores faltantes no son 0 en como en excel son NA, por lo que al calcular su z-score seguirán siendo NA
moras <- moras %>%
  mutate(
    z_salario =(moras$SALARIO-mean(moras$SALARIO, na.rm = TRUE))/ sd(moras$SALARIO, na.rm = TRUE),
    z_edad =(moras$EDAD-mean(moras$EDAD, na.rm = TRUE))/ sd(moras$EDAD, na.rm = TRUE)
  )

#ahora con esas variables ya creadas se crearan las variables para verificiar si son mayores o menores a 1,96 que retornará un true o false
moras <- moras %>%
  mutate(
    atipico_salario=(abs(z_salario) > 1.96),
    atipico_edad=(abs(z_edad) > 1.96)
  )

view(moras)
```


#Porcentaje valores faltantes
```{r}
#con col sums y is.na se calculara los na por columnas que hay en todas las columnas y adimas se divide por la cantidad de filas que hay y se multiplica por 100 para que quede en porcentaje
colSums(is.na(moras))/nrow(moras)*100
```
#Imputando los valores faltantes
```{r}
#usamos la funcion mean y is.na para imputar por la media los valores faltantes de la columna edad y salario
moras$SALARIO[is.na(moras$SALARIO)] <- mean(moras$SALARIO, na.rm = TRUE)
moras$EDAD[is.na(moras$EDAD)] <- mean(moras$EDAD, na.rm = TRUE)

#se calcula la moda de los tipos de aseguramientos
moda <- function(x) {
  #crear una tabla donde nos diga la cantidad de veces que aparece cada tipo de aseguramiento
  tabla <- table(x)
  #encontrar la frecuencia máxima de cata tipo de aseguramiento
  freq_max <- max(tabla)
  #devuelve el tipo de aseguramiento con más repeticiones, donde lo que hace es crear un vector lógico que devuelve cuál de los diferentes tipos de aseguramiento es el que tiene más frecuencia.
  moda_valor <- names(tabla)[tabla == freq_max]
  #si hay varias modas, devuelve la primera que se ecnontró
  return(moda_valor[1])
}

#se crea la variable moda_tipo donde se utiliza la funcion creada anteriormente y se pone de criterio la columna tipo aseguramiento para poder calcular la moda
#después lo que hacemos es con is.na decimos que los valores faltantes en esta columna se van a reemplazar con la moda que se encontro en la línea de arriba
moda_tipo <- moda(moras$TIPO_ASEGURAMIENTO)
moras$TIPO_ASEGURAMIENTO[is.na(moras$TIPO_ASEGURAMIENTO)] <- moda_tipo
view(moras)

```


#Gráficos cantidad de individuos por categoría
```{r}
#se usa la estructura básica para crear todos los gráficos segun el individuo, la base de datos, ggplot con el aes, despues se escoge el tipo de gráfico que en este caso sera uno de barras, se escribe el titulo, el nombre de los ejes y el theme minimal para que se vea mejor.

#también en el caso de tipos de aseguramiento usamos str_wrap para que el nombre no quede tan largo y se pueda dividir, donde ponemos que sea 15 para que el largo no sobre pase ese número y coord flip para que no se vea recargado abajo.
moras %>%
  ggplot(aes(x =str_wrap(TIPO_ASEGURAMIENTO, 15))) +
  geom_bar(fill = "steelblue") +
  labs(
    title = "Cantidad de individuos por tipo de aseguramiento",
    x = "Categoría",
    y = "Cantidad de individuos"
  ) +
  theme_minimal() +
  coord_flip()

moras %>%
  ggplot(aes(x = SEXO)) +
  geom_bar(fill = "steelblue") +
  labs(
    title = "Cantidad de individuos por sexo",
    x = "Sexo",
    y = "Cantidad de individuos"
  ) +
  theme_minimal()

moras %>%
  ggplot(aes(x = SECTOR)) +
  geom_bar(fill = "steelblue") +
  labs(
    title = "Cantidad de individuos por sector",
    x = "Sector",
    y = "Cantidad"
  ) +
  theme_minimal()

moras %>%
  ggplot(aes(x = INDICADOR_ACTIVO)) + 
  geom_bar(fill = "steelblue") +
  labs(
    title= "Cantidad de individuos según si tienen activado su seguro",
    x= "¿Tiene el seguro activo?",
    y= "Cantidad de individuos"
  ) + 
  theme_minimal()

moras %>%
  ggplot(aes(x =INDICADOR.EXTRANJERO)) +
  geom_bar(fill = "steelblue") +
  labs(
    title = "Cantidad de individuos según condición de extranjero",
    x = "¿Es extranjero?",
    y = "Cantidad de individuos"
  ) +
  theme_minimal()

moras %>%
  ggplot(aes(x = INDICADOR_MOROSO)) +
  geom_bar(fill = "steelblue") +
  labs(
    title = "Cantidad de individuos según condición de morosidad",
    x = "¿Es moroso?",
    y = "Cantidad de individuos"
  ) +
  theme_minimal()

#note que son los mismo gráficos que los que hicimos en excel, por lo que sería el mismo análisis, por lo tanto no me detendré en volver a poner lo mismo.
```

#Gráficos morosidad según variables categóricas
```{r}
#lo que hacemos primero es hacer un agrupación por cada variable y con summarrise calculamos el porcentaje de morosidad que hay con mean donde solo lo calculamos cuando este es igual a "SI"
gráfico_sexo <-moras %>%
    group_by(SEXO) %>%
    summarise(
      porcentaje_moroso = mean(INDICADOR_MOROSO == "SI") * 100
    ) %>%
    ggplot(aes(x = SEXO, y = porcentaje_moroso)) +
    geom_col(fill = "steelblue") +
    labs(
      title ="Porcentaje de morosos por sexo",
      x = "Sexo",
      y = "Porcentaje de morosos (%)"
    ) +
    theme_minimal()
print(gráfico_sexo)

gráfico_sector <-moras %>%
    group_by(SECTOR) %>%
    summarise(
      porcentaje_moroso = mean(INDICADOR_MOROSO == "SI") * 100
    ) %>%
    ggplot(aes(x = SECTOR, y = porcentaje_moroso)) +
    geom_col(fill = "steelblue") +
    labs(
      title ="Porcentaje de morosos por sector",
      x = "Sector",
      y = "Porcentaje de morosos (%)"
    ) +
    theme_minimal()
print(gráfico_sector)

#al igual que en el gráfico de tipo de aseguramiento anterior usamos str_wrap y coord flip para que sea legible el gráfico
gráfico_tipo_aseguramiento <-moras %>%
    group_by(TIPO_ASEGURAMIENTO) %>%
    summarise(
      porcentaje_moroso = mean(INDICADOR_MOROSO == "SI") * 100
    ) %>%
    ggplot(aes(x = str_wrap(TIPO_ASEGURAMIENTO, 15), y = porcentaje_moroso)) +
    geom_col(fill = "steelblue") +
    labs(
      title ="Porcentaje de morosos por tipo de aseguramiento",
      x = "TIpos de aseguramientos",
      y = "Porcentaje de morosos (%)"
    ) +
    theme_minimal() + 
    coord_flip()
print(gráfico_tipo_aseguramiento)

gráfico_activo <-moras %>%
    group_by(INDICADOR_ACTIVO) %>%
    summarise(
      porcentaje_moroso = mean(INDICADOR_MOROSO == "SI") * 100
    ) %>%
    ggplot(aes(x = INDICADOR_ACTIVO, y = porcentaje_moroso)) +
    geom_col(fill = "steelblue") +
    labs(
      title ="Porcentaje de morosos por si tienen activado su seguro o no",
      x = "¿Tienen activado su seguro?",
      y = "Porcentaje de morosos (%)"
    ) +
    theme_minimal()
print(gráfico_activo)

gráfico_extranjero <-moras %>%
    group_by(INDICADOR.EXTRANJERO) %>%
    summarise(
      porcentaje_moroso = mean(INDICADOR_MOROSO == "SI") * 100
    ) %>%
    ggplot(aes(x = INDICADOR.EXTRANJERO, y = porcentaje_moroso)) +
    geom_col(fill = "steelblue") +
    labs(
      title ="Porcentaje de morosos por si son extranjeros o no",
      x = "¿Son extranjeros?",
      y = "Porcentaje de morosos (%)"
    ) +
    theme_minimal()
print(gráfico_sexo)

#note en este caso pasa igual, los gráficos son los mismos que en excel, por lo que se hará nuevamente el análisis

```

#Gráficos morosidad según numéricas
```{r}
#lo que hacemos es agrupar por morosidad y con summarise calcular el promedio de la edad sin tomar en cuenta los NA, despues usamos al estrcutrua general para un gráfico en ggplot 2, además usamos scale_fill_manual para poder asignar colores a si es moroso o no es moroso
edad_morosidad <- moras %>%
  group_by(INDICADOR_MOROSO) %>%
  summarise(promedio_edad = mean(EDAD, na.rm = TRUE))

ggplot(edad_morosidad, aes(x = INDICADOR_MOROSO,
                           y = promedio_edad,
                           fill = INDICADOR_MOROSO)) +
  geom_col() +
  labs(
    title = "Promedio de edad según morosidad",
    x = "Moroso",
    y = "Promedio de edad"
  ) +
  scale_fill_manual(values = c("NO" = "steelblue", "SI" = "tomato")) +
  theme_minimal()

salario_morosidad <- moras %>%
  group_by(INDICADOR_MOROSO) %>%
  summarise(promedio_salario = mean(SALARIO, na.rm = TRUE))

ggplot(salario_morosidad, aes(x = INDICADOR_MOROSO,
                              y = promedio_salario,
                              fill = INDICADOR_MOROSO)) +
  geom_col() +
  labs(
    title = "Promedio de salario según morosidad",
    x = "Moroso",
    y = "Promedio de salario"
  ) +
  scale_fill_manual(values = c("NO" = "steelblue", "SI" = "tomato")) +
  theme_minimal()

#note que son los mismos gráficos que dieron en excel, por lo que no vale la pena realizar el mimso análisis otra vez, por lo que se omitirá
```

